# Generated by Django 4.2.9 on 2024-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='depth1',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
